# site.yml
- name: manage kubernetes cluster
  hosts: kube_cluster
  roles:
    - role: common  

- name: prepere kubernetes nodes workers and masters
  hosts: kube_cluster
  gather_facts: false
  roles:
    - role: swap_manage
    - role: containerd
    - role: k8s_packages
      


- name: cluster initialization and cluster network
  hosts: master-nodes
  gather_facts: false
  roles:
    - role: cluster_init
    - role: k8s_admin
    - role: cluster_network
    - role: cluster_status
      

- name: join kubernetes cluster
  hosts: kube_cluster
  gather_facts: false
  roles:
    - role: cluster_join_workers
      

