# site.yml
# kubeadmin init --control-plane-endpoint
- name: manage kubernetes cluster
  hosts: all
  roles:
    - role: common  # Always runs
      tags: always

- name: prepere kubernetes nodes workers and masters
  hosts: kube_cluster
  gather_facts: false
  roles:
    - role: swap_manage
      tags: build
    - role: containerd
      tags: build
    - role: k8s_packages
      tags: build


- name: cluster initialization and cluster network
  hosts: super-master
  gather_facts: false
  roles:
    - role: cluster_init
      tags: build  
    - role: k8s_admin
      tags: build  
    - role: cluster_network
      tags: build
    - role: cluster_status
      tags: build  


- name: join kubernetes cluster
  hosts: worker-nodes:super-master
  gather_facts: false
  roles:
    - role: cluster_join_workers
      tags: build


- name: add admin user to kubernetes masters
  hosts: master-nodes
  gather_facts: false
  roles:
    - role: k8s_admin
      tags: build

