---
- name: Deploy 3-Node RabbitMQ Cluster (Direct Helm Method)
  hosts: master
  gather_facts: false
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

  tasks:
    - name: Create RabbitMQ namespace
      kubernetes.core.k8s:
        name: rabbitmq
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploy RabbitMQ cluster
      kubernetes.core.k8s:
        state: present
        definition:
            apiVersion: rabbitmq.com/v1beta1
            kind: RabbitmqCluster
            metadata:
              name: rabbitmq-cluster
              namespace: rabbitmq
            spec:
              replicas: 2
              image: bitnamilegacy/rabbitmq:4.1.3-debian-12-r1  # <--- Add this line
              service:               # <--- Add this block
                type: NodePort
              persistence:
                storageClassName: local-path
                storage: 10Gi
              resources:
                requests:
                  cpu: 250m
                  memory: 500Mi
                limits:
                  cpu: 500m
                  memory: 1Gi